# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "iorum-acts_as_viewable"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alan Larkin"]
  s.date = "2013-02-15"
  s.description = "Adds models and methods to facilitate tracking of views of your models. Models which act_as_viewable have an instance method view! which will record a viewing of a record by the supplied IP address if and only if the IP has not viewed the record in the last n minutes."
  s.email = "alan.larkin@gmail.com"
  s.extra_rdoc_files = [
    "README",
    "README.markdown"
  ]
  s.files = [
    ".document",
    ".rspec",
    "CHANGELOG",
    "MIT-LICENSE",
    "README",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "generators/acts_as_viewable/USAGE",
    "generators/acts_as_viewable/acts_as_viewable_generator.rb",
    "generators/acts_as_viewable/templates/acts_as_viewable.rake",
    "generators/acts_as_viewable/templates/acts_as_viewable_migration.rb",
    "init.rb",
    "iorum-acts_as_viewable.gemspec",
    "lib/acts_as_viewable.rb",
    "lib/acts_as_viewable/acts_as_viewable.rb",
    "lib/acts_as_viewable/total_viewings.rb",
    "lib/acts_as_viewable/viewing.rb",
    "rails/init.rb",
    "spec/acts_as_viewable/acts_as_viewable_spec.rb",
    "spec/acts_as_viewable/total_viewings_spec.rb",
    "spec/acts_as_viewable/viewing_spec.rb",
    "spec/schema.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/iorum/acts_as_viewable"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Record IP/timeframe unique viewings of your models"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<sqlite3-ruby>, [">= 1.2.5"])
      s.add_development_dependency(%q<rspec>, ["~> 1.3"])
      s.add_development_dependency(%q<rspec-rails>, ["~> 1.3"])
      s.add_development_dependency(%q<timecop>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
    else
      s.add_dependency(%q<sqlite3-ruby>, [">= 1.2.5"])
      s.add_dependency(%q<rspec>, ["~> 1.3"])
      s.add_dependency(%q<rspec-rails>, ["~> 1.3"])
      s.add_dependency(%q<timecop>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    end
  else
    s.add_dependency(%q<sqlite3-ruby>, [">= 1.2.5"])
    s.add_dependency(%q<rspec>, ["~> 1.3"])
    s.add_dependency(%q<rspec-rails>, ["~> 1.3"])
    s.add_dependency(%q<timecop>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
  end
end

